version: "2"         # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: 100
plugins:
  sonar-java:
    enabled: true
    config:
      tests_patterns:
        - core/src/main/test/**
        - tweb/src/main/test/**
        - admin-web/src/main/test/**
      sonar.java.source: 8
